### ISSUE TITLE
Initial launch checklist

### ISSUE THREAD

**Issue by PhilippSoehnlein** [PhilippSoehnlein/star-trek-roman-timeline.de#25]
Things I should check / do after the launch:

- [x] Is Tracking working?
- [x] Launch Tweet.
- [x] Ask CrossCult and startrekromane for a retweet of launch tweet.
- [x] Thank testers tweet.
- [x] Thank Glenn Clovis for Kaemira Nebula.
- [x] Buy Icons.
- [x] Create forum announcement: <a href="http://board.fedconevents.com/index.php/Board/88-Star-Trek-Die-B%C3%BCcher-und-Comics/">Fedcon-Forum</a> → <a href="http://board.fedconevents.com/index.php/Thread/18956-Star-Trek-Roman-Timeline/">Thread</a>
- [x] Create forum announcement: <a href="http://forum.startrek.de/viewforum.php?f=12">Star-Trek.de Forum</a> → <a href="http://forum.startrek.de/viewtopic.php?f=12&t=3337">Thread</a>
- [ ] Create forum announcement: <a href="http://www.trekzone.de/community/index.php?showforum=27">Trekzone Forum</a> (waiting for account approval… giving up)
- [x] Create forum announcement: <a href="http://startrek-forum.doena-soft.de/forum/forumdisplay.php?f=41">startrek-forum.de</a> → <a href="http://startrek-forum.doena-soft.de/forum/showthread.php?p=214047">Thread</a>
- [x] Take wife out for dinner and celebrate.
